### ISSUE TITLE
macOS 系统不能使用代码ctypes.windll

### ISSUE THREAD

**Issue by Dzk2011** [virtcat/auto-shawarma#10]
/operate.py 中第8行：ctypes.windll.shcore.SetProcessDpiAwareness(PROCESS_PER_MONITOR_DPI_AWARE)
ctypes.windll 仅在 Windows 系统上有效。非 Windows 平台会因缺少 windll 模块而报错(AttributeError: module 'ctypes' has no attribute 'windll')
对于 macOS，无法运行该代码。

**Comment by virtcat** [comment]
我没有 macOS 环境可测试。建议你先注释掉这一行，看看是否工作正常。

**Comment by virtcat** [comment]
改了一下 49bd1a120ceb538766f6355647640d180b752ac0，没问题的话先 close 了
