### ISSUE TITLE
[Bug]无法正常使用

### ISSUE THREAD

**Issue by mintianzan** [virtcat/auto-shawarma#11]
使用steam版本
按0之后日志显示
Locate point 1 not detected
Fail to locate!

**Comment by mintianzan** [comment]
显示尺寸时1920*1200，125%缩放，不知道是不是这个问题。运行之后screenshot文件夹内没有图片产生。有什么可以调试的方法吗

**Comment by virtcat** [comment]
调试方法没做，screenshot目录没文件是正常的，缩放是考虑了的可以排除。可以先尝试这两个：
1. 提供一张按0识别失败时的全屏截图
2. 试试窗口模式能不能正常工作

**Comment by mintianzan** [comment]
窗口模式可以
