### ISSUE TITLE
[Bug] 多屏布局带来的截图坐标与鼠标坐标不一致的问题

### ISSUE THREAD

**Issue by I-love-study** [virtcat/auto-shawarma#2]
```python
img = numpy.array(self.sct.grab(self.sct.monitors[0]))[:, :, :3]
```

通过此方法获取到的最左上角的左上角坐标可能不是 (0,0)，例如下图所示
此时的 `monitors[0]` 信息为 `{'left': 0, 'top': -248, 'width': 4160, 'height': 2560}`
![image](https://github.com/user-attachments/assets/e09d5372-cc12-43a6-8a63-bea440c85631)
![image](https://github.com/user-attachments/assets/6a4c2b37-3f9f-4952-94b4-08055bd6ef09)

**解决方法**

https://github.com/virtcat/auto-shawarma/blob/0a3e9a5bdd665a43508cc21038913ab67a21a931/recognize.py#L157-L159
在 `recognize.py` L158 - L159 里面增加
```python
left += self.sct.monitors[0]["left"]
top += self.sct.monitors[0]["top"]
```

**Comment by virtcat** [comment]
果然是不用奇怪布局就不会想到的问题… 已修复-> 1ecc2fde73147d4b6a0bffbd7ab7a9589ccd0d13
