### ISSUE TITLE
[Bug] 在PC端经常不能完整制作一个沙威玛

### ISSUE THREAD

**Issue by jie65535** [virtcat/auto-shawarma#4]
在测试中，连续点击加料的过程中总会漏那么一两个料没加上，非常频繁出现。

经过对代码修改测试，将 `click` 和 `drag` 在移动鼠标之后加上 `spin(0.01)` 再点击即可有较大改善。

在我的场景，通过增加按下前延迟、延长按下时间、释放后延迟，可最大程度避免操作失败。

**Comment by virtcat** [comment]
改了 c1382a54917e78c06ed36f991f4851a31be9bbba
