### ISSUE TITLE
[改善建议] 4号位订单偶尔不能及时处理

### ISSUE THREAD

**Issue by jie65535** [virtcat/auto-shawarma#7]
不确定是否因为炸薯条的烟雾导致4号位订单处像素一直变化从而影响识别？

现象是有时候4号位来了，订单识别到做完了以后，但是一直不给4号位服务。

偶尔会等到耐心条快满了才突然发现似得，把订单交付。

**Comment by virtcat** [comment]
已知问题，确实是这个原因，识别结果不稳定

**Comment by jie65535** [comment]
在这个commit之后出现了新的问题，4号位的东西有时候会重复做：

![image](https://github.com/user-attachments/assets/be4ca901-e1bd-475e-8030-2b3f832b5873)

**Comment by jie65535** [comment]
可以看看这个日志

![image](https://github.com/user-attachments/assets/ae077269-131b-45b8-8bb3-9ddeb0277d55)

**Comment by virtcat** [comment]
订单的排队逻辑还比较粗糙，看这表现有两种可能：
- 如果订单太长时间没处理完（30s）会尝试重做
- 上了一部分之后一段时间内没识别到剩下的部分，之后把剩下的部分当成是新订单来处理了

可以用这个方法排除一下，改改这里的条件不让它重做，看是不是还会触发
https://github.com/virtcat/auto-shawarma/blob/7361e58240bc7b11667eab89bc7ee6ff9bfc0181/main.py#L518

**Comment by jie65535** [comment]
> 订单的排队逻辑还比较粗糙，看这表现有两种可能：
> 
> * 如果订单太长时间没处理完（30s）会尝试重做
> * 上了一部分之后一段时间内没识别到剩下的部分，之后把剩下的部分当成是新订单来处理了

从实际现象看，通常发生在4号为有2个沙威玛订单时，在提交了1个后，第2个没有马上提交。

过了一会(<10s)如果还没提交，就会检测到这个订单改变了，当作新订单来处理了。也就是你说的可能性2。

在这个issue的commit之前没有这种现象。

**Comment by jie65535** [comment]
通过以下带时间戳的日志可以看出，4号位在9秒后重新识别成了新订单。导致 swm(0,0,1,0) 多做了一份。

```log
28:20 >> Append order 3: swm(0,0,0,1),swm(0,0,1,0),cola:(0,0),fries:0,juice:1,kibbeh:0
28:20 >> Make Shawarm: swm(0,0,0,1)
28:21 >> Packed: swm(0,0,0,0)
28:21 >> Give swm(0,0,0,0) to 2
28:21 >> Make Shawarm: swm(0,0,1,0)
28:24 >> Append order 1: swm(0,0,0,0),swm(0,0,0,1),cola:(0,1),fries:2,juice:0,kibbeh:0
28:24 >> Make Shawarm: swm(0,0,0,0)
28:25 >> Packed: swm(0,0,0,1)
28:25 >> Give swm(0,0,0,1) to 3
28:26 >> Make Shawarm: swm(0,0,0,1)
28:27 >> Append order 4: swm(0,0,1,1),cola:(0,0),fries:1,juice:1,kibbeh:1
28:28 >> Make Shawarm: swm(0,0,1,1)
28:29 >> Append order 3: swm(0,0,1,0),cola:(0,0),fries:0,juice:0,kibbeh:0
28:29 >> Packed: swm(0,0,0,0),swm(0,0,1,0)
28:29 >> Give swm(0,0,0,0) to 1
28:30 >> Make Shawarm: swm(0,0,1,0)
28:31 >> Packed: swm(0,0,1,0),swm(0,0,0,1)
28:32 >> Packed: swm(0,0,1,0),swm(0,0,0,1)
28:32 >> Give swm(0,0,0,1) to 1
28:33 >> Packed: swm(0,0,1,1),swm(0,0,1,0)
28:33 >> Give swm(0,0,1,1) to 4
28:33 >> Append order 2: swm(0,0,0,1),cola:(2,0),fries:1,juice:0,kibbeh:1
28:33 >> Make Shawarm: swm(0,0,0,1)
28:35 >> Packed: swm(0,0,1,0),swm(0,0,1,0)
28:36 >> Packed: swm(0,0,1,0),swm(0,0,1,0)
28:36 >> Packed: swm(0,0,1,0),swm(0,0,1,0)
28:36 >> Give swm(0,0,1,0) to 3
28:38 >> Packed: swm(0,0,1,0)
```

**Comment by jie65535** [comment]
我回调了 https://github.com/virtcat/auto-shawarma/commit/7361e58240bc7b11667eab89bc7ee6ff9bfc0181 的代码后没再出现上述现象，但还是会出现本issue最初的问题。

**Comment by virtcat** [comment]
get，我再想想怎么解比较好…
